import {Scene,C} from './common/scene.js';
import {topics,comparisonNames} from './common/catalog.js';
import {render as mapping} from './mapping/view.js';
import {render as planning} from './planning/view.js';
import {render as trajectory} from './trajectory/view.js';
import {render as avoidance} from './avoidance/view.js';
const $=id=>document.getElementById(id),renderers={mapping,planning,trajectory,avoidance};
const defaults={resolution:.25,radius:.25,margin:.10,pointSize:.045,density:1,depth:3,slice:1.5,falloff:.7,range:2,horizon:12,rollouts:24,inflationStorage:0,inflationView:0};
let params={...defaults},topic='mapping',mode='Point cloud',t=1,playing=false,dirty=true,scene,data,cloud,last=0,lastDraw=0;
const definitions={
 inflationView:['Inflation view','select',[0,1]],
 inflationStorage:['Inflation representation','select',[0,1]],
 resolution:['Cell width (m)','select',[.1,.25,.5]],radius:['UAV radius (m)','range',.1,1.2,.05],margin:['Safety margin (m)','range',0,.8,.05],pointSize:['Point size (m)','range',.02,.12,.005],density:['Display every Nth sample','select',[1,2,4,8]],depth:['Maximum octree depth','select',[1,2,3,4,5,6]],slice:['Slice altitude (m)','range',.5,4.5,.25],falloff:['Cost falloff length (m)','range',.2,2,.1],range:['Distance color range (m)','range',.5,3,.25],horizon:['Prediction steps · cached runs','select',[6,12,18]],rollouts:['Displayed candidate rollouts','range',4,24,1]
};
function controls(){let keys=topic==='mapping'?({'Point cloud':['pointSize','density'],'Dense voxels':['resolution'],'Sparse voxels':['resolution'],'Voxel blocks':['resolution'],'Octree':['depth'],'Triangle mesh':[],'Elevation map':['resolution'],'Occupancy':['slice'],'Inflation':['inflationView','inflationStorage',params.inflationStorage===1?'depth':'resolution','radius','margin',...(params.inflationView===1?['slice']:[])],'Costmap':['slice','falloff'],'ESDF':['slice','range']}[mode]||[]):topic==='avoidance'&&['MPC','MPPI'].includes(mode)?['horizon','rollouts']:[];
 $('parameters').replaceChildren();for(let key of keys){let [label,kind,...options]=definitions[key],row=document.createElement('div');row.className='parameter';let id='param-'+key;row.innerHTML=`<label for="${id}">${label}<output>${key==='inflationView'?['Whole volume','Horizontal slice'][params[key]]:key==='inflationStorage'?['Voxel grid','Octree'][params[key]]:params[key]}</output></label>`;let input=document.createElement(kind==='select'?'select':'input');input.id=id;if(kind==='select')options[0].forEach(v=>{let opt=document.createElement('option');opt.value=v;opt.textContent=key==='inflationView'?['Whole volume','Horizontal slice'][v]:key==='inflationStorage'?['Voxel grid','Octree'][v]:v;input.append(opt);});else{input.type='range';[input.min,input.max,input.step]=options;}input.value=params[key];input.addEventListener('input',()=>{params[key]=+input.value;row.querySelector('output').textContent=key==='inflationView'?['Whole volume','Horizontal slice'][+input.value]:key==='inflationStorage'?['Voxel grid','Octree'][+input.value]:input.value;if(['inflationStorage','inflationView'].includes(key))controls();dirty=true;});row.append(input);$('parameters').append(row);}
 if(topic==='planning'&&mode==='Comparison'){for(let name of comparisonNames){let label=document.createElement('label');label.className='compare-toggle';let input=document.createElement('input');input.type='checkbox';input.checked=params.visible?.[name]!==false;input.onchange=()=>{params.visible??={};params.visible[name]=input.checked;dirty=true;};label.append(input,document.createTextNode(name));$('parameters').append(label);}}
}
function setMode(value){mode=value;if(scene){const wide=topic==='mapping'&&mode==='Point cloud';if(scene.wide!==wide){scene.wide=wide;scene.reset();}}$('demo').value=value;const previous=params;params={...defaults};if(topic==='mapping'&&['Occupancy','Costmap','ESDF'].includes(mode)){params.pick=previous.pick;params.slice=previous.slice;params.falloff=previous.falloff;params.range=previous.range;}t=topic==='mapping'?1:0;playing=false;$('play').textContent='▶ Play';$('concept').textContent=topics[topic].modes[mode][0];$('explanation').textContent=topics[topic].modes[mode][1];controls();dirty=true;}
function setTopic(value){topic=topics[value]?value:'mapping';let spec=topics[topic];$('eyebrow').textContent=spec.eyebrow;$('topic-title').textContent=spec.label;$('intro').textContent=spec.intro;$('demo').replaceChildren();let group=null;for(let name of Object.keys(spec.modes)){if(topic==='mapping'&&['Point cloud','Inflation','Occupancy'].includes(name)){group=document.createElement('optgroup');group.label=name==='Point cloud'?'Geometry and storage':name==='Inflation'?'Collision processing':'Information at each location';$('demo').append(group);}let o=document.createElement('option');o.value=name;o.textContent=name;(group||$('demo')).append(o);}document.querySelectorAll('#topics button').forEach(e=>e.classList.toggle('active',e.dataset.topic===topic));setMode(Object.keys(spec.modes)[0]);}
Object.entries(topics).forEach(([key,spec],i)=>{let b=document.createElement('button');b.innerHTML=`<span class="num">0${i+1}</span>${spec.label}`;b.dataset.topic=key;b.onclick=()=>{location.hash=key;};$('topics').append(b);});
window.addEventListener('hashchange',()=>setTopic(location.hash.slice(1)));$('demo').onchange=e=>setMode(e.target.value);
function toggle(){if(t>=1)t=0;playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Play';dirty=true;}
$('play').onclick=toggle;$('step').onclick=()=>{playing=false;$('play').textContent='▶ Play';t=Math.min(1,t+stepSize());dirty=true;};
function stepSize(){if(topic==='planning'){let p=data?.planners[mode];return 1/Math.max(1,p?.visited?.length||p?.events?.length||100);}if(topic==='avoidance'&&['MPC','MPPI'].includes(mode))return 1/data.avoidance.controllers[String(params.horizon)][mode].frames.length;if(topic==='avoidance'&&data?.avoidance.local?.[mode])return 1/data.avoidance.local[mode].frames.length;if(topic==='trajectory'&&mode==='CHOMP')return 1/data.trajectory.chomp.length;return .01;}
$('reset').onclick=()=>{params={...defaults};setMode(mode);t=0;scene.reset();};$('progress').oninput=e=>{t=+e.target.value/1000;dirty=true;};$('perspective').onclick=() =>scene.reset();$('top').onclick=()=>scene.reset(true);$('camera-reset').onclick=()=>scene.reset();$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.key==='ArrowRight'){e.preventDefault();$('step').click();}if(e.key.toLowerCase()==='r')$('reset').click();if(e.key.toLowerCase()==='c')scene.reset();if(e.key>='1'&&e.key<='4')location.hash=Object.keys(topics)[+e.key-1];});
function metric(label,value){let e=document.createElement('div');e.className='metric';let l=document.createElement('span');l.textContent=label;let v=document.createElement('strong');v.textContent=value;e.append(l,v);$('metrics').append(e);}
function plot(values,index,label,color,times){let canvas=$('chart');canvas.style.display='block';let c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.font='11px system-ui';c.fillStyle='#a5b7cb';c.fillText(label,13,19);let min=Math.min(0,...values),max=Math.max(...values,min+.001),x=i=>15+i/(values.length-1)*(w-30),y=v=>h-23-(v-min)/(max-min)*(h-55);c.strokeStyle='#2b4058';c.beginPath();c.moveTo(15,30);c.lineTo(15,h-23);c.lineTo(w-15,h-23);c.stroke();c.strokeStyle=color;c.lineWidth=1.7;c.beginPath();values.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.stroke();c.fillStyle='white';c.beginPath();c.arc(x(index),y(values[index]),3,0,Math.PI*2);c.fill();c.fillStyle='#92a7bd';c.font='9px monospace';c.fillText(max.toFixed(1),18,33);c.fillText(times?times.at(-1).toFixed(1)+' s':'iteration / sample',w-110,h-7);}
function histogram(values,columns,rows,selected){const canvas=$('chart');canvas.style.display='block';const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#bacbdf';c.font='10px system-ui';c.fillText('3D VFH · elevation ↑ / azimuth →',12,16);const dx=(w-36)/columns,dy=(h-35)/rows;values.forEach((v,i)=>{const x=25+(i%columns)*dx,y=23+(rows-1-Math.floor(i/columns))*dy;c.fillStyle=i===selected?'#ffffff':v?'#d36975':'#319a82';c.fillRect(x,y,dx-1,dy-.5);});c.font='8px system-ui';c.fillStyle='#92a7bd';c.fillText('+90°',1,28);c.fillText('−90°',1,h-5);}
function table(rows){let e=$('comparison');e.style.display='block';e.innerHTML='<table><thead><tr><th>PLANNER</th><th>PREPARE</th><th>NODES</th><th>LENGTH</th><th>CLEARANCE</th></tr></thead><tbody>'+rows.map(r=>`<tr><td style="color:${r.color}">${r.name}</td><td>${r.time}</td><td>${r.nodes}</td><td>${r.length}</td><td>${r.clearance}</td></tr>`).join('')+'</tbody></table>';}
function legend(){let keys=topic==='mapping'?(mode==='Occupancy'?['dynamic','free']:mode==='Inflation'?['occupied','inflated']:['occupied']):topic==='avoidance'?['initial','path','dynamic','drone']:['occupied','visited','frontier','path','initial','goal'];const labels={occupied:'Occupied / geometry',inflated:'Forbidden region',free:'Known free',visited:'Explored / candidates',frontier:'Frontier / sample',path:topic==='avoidance'?'Local prediction':'Result / current path',initial:topic==='avoidance'?'Global path':'Initial / baseline',goal:'Goal',dynamic:topic==='mapping'?'Occupied':'New obstacle',drone:'Actual motion'};$('legend').innerHTML=keys.map(k=>`<span class="legend-item"><i style="background:${topic==='mapping'&&mode==='Occupancy'&&k==='free'?'#3da997':C[k]}"></i>${labels[k]}</span>`).join('');}
function draw(){scene.clear();const key=$('map-key');key.style.display=topic==='mapping'&&['Inflation','Occupancy','Costmap','ESDF'].includes(mode)?'block':'none';if(key.style.display==='block')key.innerHTML=mode==='Inflation'?('<strong>ROBOT SIZE → FORBIDDEN SPACE</strong><p>Radius '+params.radius.toFixed(2)+' + margin '+params.margin.toFixed(2)+' = '+(params.radius+params.margin).toFixed(2)+' m</p><span>'+(params.inflationStorage===0?(Math.ceil(((params.radius+params.margin)*t-1e-10)/params.resolution)+' extra layers × '+(100*params.resolution).toFixed(0)+' cm cells'):'Adaptive leaves · finest '+(10/2**params.depth).toFixed(3)+' m')+'</span>'):mode==='Occupancy'?'<strong>OCCUPANCY · yes / no</strong><div class="binary-key"><span>■ occupied · 1</span><span>■ free · 0</span></div>':mode==='Costmap'?'<strong>COST · penalty, not metres</strong><div class="color-ramp cost"></div><div class="ramp-labels"><span>0 · preferred</span><span>100 · obstacle</span></div>':'<strong>ESDF · signed distance in metres</strong><div class="color-ramp distance"></div><div class="ramp-labels"><span>0 m · surface</span><span>'+params.range+' m+</span></div>';
$('metrics').replaceChildren();$('chart').style.display='none';$('comparison').style.display='none';legend();renderers[topic]({scene,data,cloud,mode,t,params,metric,plot,histogram,table,note:text=>$('note').textContent=text});$('progress').value=Math.round(t*1000);$('progress-label').textContent=String(Math.round(t*100)).padStart(2,'0')+'%';$('scene-subtitle').textContent=topic==='mapping'&&mode==='Point cloud'?'Original hangar cloud · metres · Z up':'Conservative rack envelopes · 10 × 10 × 5 m · Z up';window.__lab={topic,mode,progress:t,ready:true,objects:scene.layer.children.length};}
function duration(){if(topic==='avoidance'&&data?.avoidance.local?.[mode]){let c=data.avoidance.local[mode];return c.frames.length*c.dt;}if(topic==='avoidance'&&['MPC','MPPI'].includes(mode)){let c=data.avoidance.controllers[String(params.horizon)][mode];return c.frames.length*c.dt;}if(topic==='trajectory'){if(mode==='Minimum snap')return data.trajectory.snap.duration;if(mode==='Minimum jerk')return data.trajectory.jerk.duration;}return topic==='mapping'?12:18;}
function tick(time){let dt=Math.min((time-last)/1000,.1);last=time;if(playing){t=Math.min(1,t+dt*(+$('speed').value)/duration());dirty=true;if(t===1){playing=false;$('play').textContent='▶ Play';}}if(dirty&&time-lastDraw>85){draw();dirty=false;lastDraw=time;}scene.render();requestAnimationFrame(tick);}
try{
 const [json,bin]=await Promise.all([fetch('./precomputed/lecture.json').then(r=>{if(!r.ok)throw Error('Missing prepared lecture dataset.');return r.json();}),fetch('./assets/hangar-points.bin').then(r=>{if(!r.ok)throw Error('Missing point-cloud asset.');return r.arrayBuffer();})]);data=json;let f=new Float32Array(bin);cloud=Array.from({length:f.length/3},(_,i)=>Array.from(f.subarray(i*3,i*3+3)));scene=new Scene($('viewport'));setTopic(location.hash.slice(1));$('loading').style.display='none';let down=null;scene.renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);scene.renderer.domElement.addEventListener('pointerup',e=>{if(topic==='mapping'&&['Occupancy','Costmap','ESDF'].includes(mode)&&down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<4){let p=scene.pick(e,+params.slice);if(p&&p[0]>=0&&p[0]<=10&&p[1]>=2&&p[1]<=12){params.pick=p;dirty=true;}}});requestAnimationFrame(tick);
}catch(err){$('loading').textContent='Unable to start: '+err.message+' Run ./run_mapping.sh and open the printed local URL. A WebGL2-capable browser is required.';console.error(err);}
