import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/#mapping');await page.waitForFunction(()=>window.__lab?.ready);
 assert.equal(await page.locator('#topics button').count(),4);
 await page.selectOption('#demo','Dense voxels');assert.equal(await page.locator('#param-resolution').inputValue(),'0.1');
 for(const width of ['0.1','0.25','0.5']){await page.selectOption('#param-resolution',width);await page.waitForTimeout(200);}
 await page.selectOption('#demo','Octree');const started=Date.now();await page.selectOption('#param-depth','6');await page.waitForFunction(()=>[...document.querySelectorAll('.metric')].some(e=>e.textContent==='Maximum depth6'));console.log('Depth 6 ready in',Date.now()-started,'ms');await page.screenshot({path:'tests/octree.png'});
 await page.selectOption('#demo','Inflation');await page.selectOption('#param-inflationStorage','1');assert.equal(await page.locator('#param-resolution').count(),0);await page.selectOption('#param-depth','6');await page.waitForTimeout(200);await page.selectOption('#param-inflationStorage','0');await page.locator('#progress').evaluate(e=>{e.value='1000';e.dispatchEvent(new Event('input'));});await page.waitForTimeout(200);await page.screenshot({path:'tests/inflation.png'});
 await page.selectOption('#demo','ESDF');await page.locator('#param-slice').fill('2.75');await page.waitForTimeout(150);await page.locator('#top').click();await page.locator('#viewport canvas').click({position:{x:650,y:430}});await page.waitForTimeout(200);let probe=await page.locator('.metric').filter({hasText:'Probe · x / y'}).textContent();await page.selectOption('#demo','Occupancy');await page.waitForTimeout(200);assert.equal(await page.locator('#param-slice').inputValue(),'2.75');assert.equal(await page.locator('.metric').filter({hasText:'Probe · x / y'}).textContent(),probe);await page.selectOption('#demo','Costmap');await page.waitForTimeout(200);assert.equal(await page.locator('.metric').filter({hasText:'Probe · x / y'}).textContent(),probe);await page.screenshot({path:'tests/information.png'});
 await page.locator('[data-topic="planning"]').click();await page.selectOption('#demo','Comparison');let toggles=page.locator('.compare-toggle input');assert.equal(await toggles.count(),9);for(const input of await toggles.all())await input.uncheck();await page.waitForTimeout(250);assert.equal(await page.locator('#comparison tbody tr').count(),0);await page.locator('.compare-toggle').filter({hasText:/^PRM$/}).locator('input').check();await page.waitForTimeout(200);assert.equal(await page.locator('#comparison tbody tr').count(),1);await page.locator('#reset').click();await page.waitForTimeout(250);assert.equal(await page.locator('#comparison tbody tr').count(),9);
 await page.selectOption('#demo','D* Lite');for(const phase of [125,375,625,950]){await page.locator('#progress').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input'));},phase);await page.waitForTimeout(150);}await page.screenshot({path:'tests/dstar.png'});
 await page.locator('[data-topic="trajectory"]').click();assert.ok(!(await page.locator('#demo option').allTextContents()).includes('Path vs trajectory'));await page.selectOption('#demo','STOMP');await page.locator('#progress').evaluate(e=>{e.value='500';e.dispatchEvent(new Event('input'));});await page.waitForTimeout(200);await page.screenshot({path:'tests/stomp.png'});
 assert.deepEqual(errors,[]);console.log('Revision interaction checks passed.');
}finally{await browser.close();}
