import * as THREE from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
export const C={occupied:'#8195b2',inflated:'#ee9c55',visited:'#538bc6',frontier:'#ffe39a',path:'#5ee5c0',initial:'#e0b0ed',drone:'#ffffff',goal:'#bbec67',dynamic:'#ff7186',free:'#324c64',unknown:'#17263d'};
export class Scene {
 constructor(host){
  this.host=host;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#0a1220');this.scene.fog=new THREE.Fog('#0a1220',35,85);
  this.camera=new THREE.PerspectiveCamera(43,1,.05,150);this.camera.up.set(0,0,1);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(this.renderer.domElement);
  this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.maxDistance=65;this.controls.minDistance=2;
  this.scene.add(new THREE.HemisphereLight(0xccddff,0x263a42,2.5));let light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,-4,14);this.scene.add(light);
  this.base=new THREE.Group();this.layer=new THREE.Group();this.scene.add(this.base,this.layer);
  let grid=new THREE.GridHelper(30,60,0x2d4057,0x16273c);grid.rotation.x=Math.PI/2;grid.position.set(8,6,-.04);this.base.add(grid);
  this.reset();new ResizeObserver(()=>this.resize()).observe(host);this.resize();
 }
 resize(){let w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 reset(top=false){const wide=this.wide;this.camera.position.set(...(top?(wide?[9,6,34]:[5,7,23]):(wide?[27,-19,21]:[15,-7,12])));this.controls.target.set(...(wide?[9,6,2.5]:[5,7,1.8]));this.controls.update();}
 clear(){this.layer.traverse(o=>{o.geometry?.dispose();if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});this.layer.clear();}
 render(){this.controls.update();this.renderer.render(this.scene,this.camera);}
 box(lo,hi,color=C.occupied,opacity=1,wire=false){let s=hi.map((v,i)=>v-lo[i]);let geom=new THREE.BoxGeometry(...s);let mat=wire?new THREE.LineBasicMaterial({color,transparent:true,opacity}):new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,roughness:.7,depthWrite:opacity>.5});let obj=wire?new THREE.LineSegments(new THREE.EdgesGeometry(geom),mat):new THREE.Mesh(geom,mat);if(wire)geom.dispose();obj.position.set(...lo.map((v,i)=>(v+hi[i])/2));this.layer.add(obj);return obj;}
 cubes(points,size,color,opacity=.6,colors=null){if(!points.length)return;let mesh=new THREE.InstancedMesh(new THREE.BoxGeometry(size*.94,size*.94,size*.94),new THREE.MeshStandardMaterial({color:colors?'white':color,transparent:opacity<1,opacity,roughness:.75,depthWrite:opacity>.5}),points.length);let mat=new THREE.Matrix4();points.forEach((p,i)=>{mat.makeTranslation(...p);mesh.setMatrixAt(i,mat);if(colors)mesh.setColorAt(i,new THREE.Color(colors[i]));});mesh.instanceMatrix.needsUpdate=true;this.layer.add(mesh);return mesh;}
 points(points,color=C.visited,size=.06,colors=null){if(!points.length)return;let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points.flat(),3));if(colors)g.setAttribute('color',new THREE.Float32BufferAttribute(colors.flatMap(c=>new THREE.Color(c).toArray()),3));let o=new THREE.Points(g,new THREE.PointsMaterial({color:colors?'white':color,size,vertexColors:!!colors,transparent:true,opacity:.85}));this.layer.add(o);return o;}
 line(points,color=C.path,opacity=1){if(points.length<2)return;let g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));let o=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity}));this.layer.add(o);return o;}
 segments(edges,color,opacity=.5){if(!edges.length)return;let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(edges.flat(2),3));let o=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}));this.layer.add(o);}
 path(points,color=C.path,r=.038){if(points.length<2)return;const curve=new THREE.CurvePath();for(let i=1;i<points.length;i++)if(new THREE.Vector3(...points[i]).distanceTo(new THREE.Vector3(...points[i-1]))>1e-6)curve.add(new THREE.LineCurve3(new THREE.Vector3(...points[i-1]),new THREE.Vector3(...points[i])));if(!curve.curves.length)return;let mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.max(points.length*2,100),r,5,false),new THREE.MeshBasicMaterial({color}));this.layer.add(mesh);}
 sphere(p,r,color,opacity=1){let o=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,wireframe:opacity<.3}));o.position.set(...p);this.layer.add(o);return o;}
 drone(p){this.sphere(p,.15,C.drone);for(let x of [-1,1])for(let y of [-1,1]){let q=[p[0]+x*.27,p[1]+y*.27,p[2]];this.line([p,q],C.drone);let ring=new THREE.Mesh(new THREE.TorusGeometry(.13,.025,5,16),new THREE.MeshBasicMaterial({color:C.path}));ring.position.set(...q);this.layer.add(ring);}}
 environment(data,opacity=.7){data.boxes.forEach(([a,b])=>{this.box(a,b,C.occupied,opacity);this.box(a,b,'#b6cee1',.3,true);for(let z of [1,2,3])this.box([a[0],a[1],z],[b[0],b[1],z+.035],'#d4dfee',.8);});this.box(data.bounds[0],data.bounds[1],'#405c7c',.25,true);this.sphere(data.start,.15,C.initial);this.sphere(data.goal,.2,C.goal);}
 pick(event,z){let rect=this.renderer.domElement.getBoundingClientRect();let mouse=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);let ray=new THREE.Raycaster();ray.setFromCamera(mouse,this.camera);let p=new THREE.Vector3();return ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,0,1),-z),p)?p.toArray():null;}
 ellipsoid(start,goal,length){let a=new THREE.Vector3(...start),b=new THREE.Vector3(...goal),d=a.distanceTo(b);if(length<d)return;let obj=new THREE.Mesh(new THREE.SphereGeometry(1,24,12),new THREE.MeshBasicMaterial({color:C.goal,wireframe:true,transparent:true,opacity:.17}));obj.position.copy(a.add(b).multiplyScalar(.5));obj.scale.set(length/2,Math.sqrt(length*length-d*d)/2,Math.sqrt(length*length-d*d)/2);obj.quaternion.setFromUnitVectors(new THREE.Vector3(1,0,0),new THREE.Vector3(...goal).sub(new THREE.Vector3(...start)).normalize());this.layer.add(obj);}
}
